inherit_from:
  - .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6


Layout/CaseIndentation:
  EnforcedStyle: end

# Array indentation should be consistent with method/variable definition.
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

# %q() is easier to grep than %()
Style/BarePercentLiterals:
  EnforcedStyle: percent_q

# Pick one option for consistency.
Style/EmptyMethod:
  EnforcedStyle: expanded

# Be consistent. The trailing comma also allows easy reordering.
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

# Be consistent. The trailing comma also allows easy reordering.
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
