inherit_from:
  - .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6


# %q() is easier to grep than %()
Style/BarePercentLiterals:
  EnforcedStyle: percent_q

# Be consistent. The trailing comma also allows easy reordering.
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
